### ISSUE TITLE
Is it necessary to add 'p_type' tag to  compatible the old version?

### ISSUE THREAD

**Issue by Blank-Xu** [casbin/xorm-adapter#10]
Two days ago I have a pr [improve](https://github.com/casbin/xorm-adapter/commit/bc08a0dfc382135c046d51b01377bacad99c8a61) , and it has been merged.

On line 28:
`Ptype string `xorm:"varchar(100) index"``
would not compatible the old version if someone upgrade production envrionment with data.

So is it necessary add to add a tag:

**Comment by hsluoyz** [comment]
Thanks for the report. I have reverted the PR.
