### ISSUE TITLE
the func SavePolicy will drop table?

### ISSUE THREAD

**Issue by wangwei123** [casbin/xorm-adapter#14]
https://github.com/casbin/xorm-adapter/blob/9b17d80119cb29c6d09806fbe3dc97fcbec3c01e/adapter.go#L226-L249

the func SavePolicy will drop table?

**Comment by hsluoyz** [comment]
Hi @wangwei123 , as you said in the code, it will drop the table.

If you don't think it's a good behavior, please explain it. Better with PR.

**Comment by hsluoyz** [comment]
Closed as stale.
