### ISSUE TITLE
Connect to specific table

### ISSUE THREAD

**Issue by julisch94** [casbin/xorm-adapter#3]
How do I connect to a specific table inside an sqlite database?
`adapter := xormadapter.NewAdapter("sqlite3", "./database.db", true)` connects successfully with my sqlite database, but creates a default table **casbin_rules**.

`adapter := xormadapter.NewAdapter("sqlite3", "./database.db/mytable", true)` unfortunately interprets `database.db` as directory.

**Comment by hsluoyz** [comment]
Currently Xorm will automatically name the table after the struct being stored. based on [Xorm docs](http://gobook.io/read/github.com/go-xorm/manual-en-US/chapter-02/1.mapping.html). The struct is:
```go
type CasbinRule struct {
	PType string `xorm:"varchar(100)"`
	V0    string `xorm:"varchar(100)"`
	V1    string `xorm:"varchar(100)"`
	V2    string `xorm:"varchar(100)"`
	V3    string `xorm:"varchar(100)"`
	V4    string `xorm:"varchar(100)"`
	V5    string `xorm:"varchar(100)"`
}
```

So the default table name would be ``casbin_rule``. And the table would be just as the struct definition. So basically you can't reuse an existing table that has other structures. Would you tell me why you want to rename the table name?

**Comment by julisch94** [comment]
I was wondering if there's a way to reconfigure the names of the tabes and its columns. I saw the struct you've posted already in the code but found no way to change it.

So I can't change the used database name. That's alright for me.
Does that mean that I can't change the column names in `casbin_rule` (p_type, v1, etc.) either?

**Comment by hsluoyz** [comment]
> I can't change the used database name.

I don't understand. The DB for SQLite is the .db file, which is controlled by you. 

> Does that mean that I can't change the column names in casbin_rule (p_type, v1, etc.) either?

I think the simplest and most direct way to do it is renaming the struct ``CasbinRule`` and its members. Then the table and column names will change at the same time. You can do this job within a IDE, so all references will change too.

**Comment by julisch94** [comment]
Thank you very much. I will try that.

**Comment by julisch94** [comment]
By the way, it worked. Renaming the struct `CasbinRule` and its members makes the created table and its columns be named accordingly.
