### ISSUE TITLE
the error returned it not pg.Error

### ISSUE THREAD

**Issue by Jimexist** [casbin/xorm-adapter#4]
https://github.com/casbin/xorm-adapter/blob/master/adapter.go#L93

**Comment by hsluoyz** [comment]
The debugging shows ``err`` is an object of ``*github.com/lib/pg.Error``, as shown in this figure.

Can you explain more about how to reproduce your issue?

![image](https://user-images.githubusercontent.com/3787410/29202174-0d1a8b48-7e98-11e7-963d-bcd538b2be0c.png)

**Comment by hsluoyz** [comment]
Close as stale.
