### ISSUE TITLE
SavePolicy reports "No element on slice when insert" error when the model's policy is null

### ISSUE THREAD

**Issue by liupzmin** [casbin/xorm-adapter#40]
hi, I am using SavePolicy of enforcer in my program to save policies manully. but I get an xorm error which is ErrNoElementsOnSlice when the model is null. I found the following code:

```go
// SavePolicy saves policy to database.
func (a *Adapter) SavePolicy(model model.Model) error {
	err := a.dropTable()
	if err != nil {
		return err
	}
	err = a.createTable()
	if err != nil {
		return err
	}

	lines := make([]*CasbinRule, 0, 64)

	for ptype, ast := range model["p"] {
		for _, rule := range ast.Policy {
			line := a.genPolicyLine(ptype, rule)
			lines = append(lines, line)
		}
	}

	for ptype, ast := range model["g"] {
		for _, rule := range ast.Policy {
			line := a.genPolicyLine(ptype, rule)
			lines = append(lines, line)
		}
	}

	_, err = a.engine.Insert(&lines)

	return err
}
````

I want to know whether we can add a length check about lines in this function to solve the problem?

**Comment by hsluoyz** [comment]
@liupzmin you need to check whether `model` is null before calling this function.

**Comment by liupzmin** [comment]
> @liupzmin you need to check whether `model` is null before calling this function.
@hsluoyz Please, correct me if I'm wrong. Consider this scenario, my goal is to remove all policies, which is not possible in the current situation.

**Comment by hsluoyz** [comment]
@liupzmin you should call `ClearPolicy()` first, then `SavePolicy()`

**Comment by liupzmin** [comment]
> @liupzmin you should call `ClearPolicy()` first, then `SavePolicy()`


I don't understand what you mean. the `ClearPolicy()` just set `policy` to nil, `SavePolicy()` will collect the `lines` of policies, and then insert it to db, the slice of `lines` that collected by `SavePolicy()` is empty now, this is why `a.engine.Insert(&lines)` reports error .

**Comment by hsluoyz** [comment]
@closetool

**Comment by hsluoyz** [comment]
@liupzmin did you try what I said. Does it work?

**Comment by liupzmin** [comment]
> @liupzmin did you try what I said? Does it work?

yes, I have tried,  Please see the attachment screenshot：

![casbin](https://user-images.githubusercontent.com/15135871/118109601-fc960300-b413-11eb-8625-3463531f8a3f.png)

**Comment by liupzmin** [comment]
Although the final logical result is correct, I mean, I don't want to get an error.

**Comment by liupzmin** [comment]
may be we can do this:

```go
	for ptype, ast := range model["p"] {
		for _, rule := range ast.Policy {
			line := a.genPolicyLine(ptype, rule)
			lines = append(lines, line)
		}
	}

	for ptype, ast := range model["g"] {
		for _, rule := range ast.Policy {
			line := a.genPolicyLine(ptype, rule)
			lines = append(lines, line)
		}
	}
        // check here to  avoid inserting empty slice
        if len(lines) <= 0 {
	    return nil
        }

        _, err = a.engine.Insert(&lines)

        return err
```

**Comment by hsluoyz** [comment]
@tson1111
