### ISSUE TITLE
[Question] Can I configure casbin xorm to "skip" table creation ?

### ISSUE THREAD

**Issue by atreyamj** [casbin/xorm-adapter#56]
**What's your scenario? What do you want to achieve?**
 I am creating a cached enforcer in casbin and using XORM to store my policies to store my policies on a cloud managed Postgres DB. 
It looks like casbin internally calls : https://github.com/xormplus/xorm/blob/master/session_schema.go#L236 
whenever it wants to connect to the DB and to determine whether the table needs to be created or not. 
This query is long running seems to cause time outs on our end. 

Question - Is there any way I can specify casbin to NOT create the tables and assume that the table is created  and skip this call altogether ?
Or is there any other way we can work around the time outs?

Thank You!

**Comment by hsluoyz** [comment]
@atreyamj can you make a PR to: https://github.com/casbin/xorm-adapter to support what you said?

**Comment by thekartikeyamishra** [comment]
I understand your concern about the long-running query causing timeouts. To work around this issue, you can create a custom adapter that inherits from the XORM adapter and overrides the **initAdapter** method. This way, you can skip the table creation check and assume that the table already exists.  
### ### 
**My suggestion** 

- First, create a new Go file for your custom adapter, e.g., **custom_xorm_adapter.go**. 
- Define your custom adapter struct and embed the **xormadapter.Adapter** struct.
- Create a constructor function for your custom adapter.
- Override the **initAdapter** method to skip the table creation check.
- Now, you can use your custom adapter when creating a Casbin enforcer.

[go-issue.zip](https://github.com/casbin/xorm-adapter/files/11569310/go-issue.zip)

**Comment by hsluoyz** [comment]
@PokIsemaine

**Comment by atreyamj** [comment]
@hsluoyz and @thekartikeyamishra , thank you so much for your responses. Apologies in the delay in my response as I was away. 

I will try your suggestions of custom adapter and if that doesnt work will circle back on the PR. :) 

Really appreciate the responses ! 
Also, to re-iterate this is NOT a casbin issue but rather a DB issue. Hence the request to see if we can have connection without having to create table via casbin. 

I think the custom adapter should fix it.

**Comment by hsluoyz** [comment]
Closed for now
