### ISSUE TITLE
Primary key support?

### ISSUE THREAD

**Issue by eahrend** [casbin/xorm-adapter#6]
Hey,

So I wanted to add a column to my casbin table, specifically a primary key so I can identify rules if I do SQL queries by ID for ease of identification. Is that possible, I know currently there is no support for it but is there a reason for this?

**Comment by hsluoyz** [comment]
I don't think adding ID to policy rules is a necessity. In Casbin, policy rules only have order under certain conditions (for priority model). There is no way to identify one rule. But you can add customized support for this adapter.

**Comment by eahrend** [comment]
Yeah, I created a fork to support the database I'm using. The idea is to take the casbin rule, give them an ID which is assigned to a table with a human readable name in a separate table.

**Comment by hsluoyz** [comment]
So you want to merge the change to this repo? I don't know if it affects other users due to the add of this ID. Do you have any suggestion for a better way to solve it?

**Comment by hsluoyz** [comment]
Closed as stale.
