### ISSUE TITLE
Fails to connect to pg 16.1

### ISSUE THREAD

**Issue by jetaggart** [casbin/xorm-adapter#61]
Using PG 16.1 or 15.5, the adapter fails to connect:

`error: adapter: pq: trailing junk after parameter at or near "$1A"`

```
a, err := xormadapter.NewAdapter("postgres", "dbname=dbname user=admin password=admin host=localhost port=5432 sslmode=disable", true)
```
OR
```
a, err := xormadapter.NewAdapter("postgres", "user=admin password=admin host=localhost port=5432 sslmode=disable")
```

Both fail. It works the first time, it will create the casbin_rule table and perform a query. The second time I boot the application I get the above error.

**Comment by hsluoyz** [comment]
@jetaggart I can't reproduce your issue. We have unit test at:

https://github.com/casbin/xorm-adapter/blob/1089d551d1211e2450d3bebc4a7e713381442c58/adapter_test.go#L357-L387

1. The unit test has passed in the GitHub CI:
2. I also tested locally with my localhost postgres for multiple times, also no issue

![image](https://github.com/casbin/xorm-adapter/assets/3787410/8e129f56-8ea0-4ac3-b04b-7d7ca58f7e70)

![image](https://github.com/casbin/xorm-adapter/assets/3787410/22a48f60-38fd-44d3-94d4-0eb0ce140fc6)

**Comment by jetaggart** [comment]
Hmm very strange. I run all my local pg instances out of docker compose, maybe it's something with that. I ended up using a different adapter (database/sql) and that's working. Feel free to close if it's not reproducible.

**Comment by jetaggart** [comment]
Also, it worked the first time it connected. Connected and migrated just fine, subsequent connects failed to boot. Does your test connect, disconnect, then reconnect?

**Comment by hsluoyz** [comment]
@jetaggart I think I have, I run this test for multiple times (comment the mysql code):

https://github.com/casbin/xorm-adapter/blob/1089d551d1211e2450d3bebc4a7e713381442c58/adapter_test.go#L357-L387
