### ISSUE TITLE
Load Filtered policy

### ISSUE THREAD

**Issue by vtolstov** [casbin/xorm-adapter#7]
Hi! Do you have plans to add ability to load filtered policy?

**Comment by hsluoyz** [comment]
Sorry for the late response. I missed this issue.. We will try to solve it, but it may be slow. Can you send a PR for it?

**Comment by hsluoyz** [comment]
@00LT00 @dovics can anyone take this VERY OLD issue?

**Comment by hsluoyz** [comment]
@vtolstov this issue has been solved in: https://github.com/casbin/xorm-adapter/pull/31
